import type { Metadata } from "next";
import { Eater, Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Docks from "./Dock";
import Header from "@/components/Header";

<link
  href="https://fonts.googleapis.com/css2?family=Eater&family=Geist:wght@100..900&family=Sora:wght@100..800&display=swap"
  rel="stylesheet"
/>;

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const eater = Eater({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-eater",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${eater.variable} antialiased`}
      >
        <div className={eater.className}>
          <Header />
          {children}

          <Docks />
        </div>
      </body>
    </html>
  );
}
